#!/bin/bash

UPDATE_PATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo -e "\033[33mUpdate path: $UPDATE_PATH\033[0m"

if [ ! -d "$UPDATE_PATH" ]; then
    echo -e "\033[31mThe path $UPDATE_PATH does not exist\033[0m"
    exit 1
fi
# Path: updateconf
cd $UPDATE_PATH

# Update the repository
git pull

# update files in .scripts
SCRIPTS_FOLDER=~/.scripts
## Create the folder if it does not exist
if [ ! -d "$SCRIPTS_FOLDER" ]; then
    echo -e "\033[33mCreating the folder $SCRIPTS_FOLDER\033[0m"
    # Create the folder
    mkdir $SCRIPTS_FOLDER
fi
## copy the files
ls .scripts | while read file; do
    cp -f .scripts/$file $SCRIPTS_FOLDER/$file
    echo -e "\033[33m$file added to .script\033[0m"
done

# add updateconf to .scripts
if [ ! -f "$SCRIPTS_FOLDER/updateconf" ]; then
    echo "#!/bin/bash
    UPDATE_PATH=$UPDATE_PATH
    cd \$UPDATE_PATH
    git pull
    cd - > /dev/null
    bash \$UPDATE_PATH/updateconf" > $SCRIPTS_FOLDER/updateconf
    chmod +x $SCRIPTS_FOLDER/updateconf
    echo -e "\033[33mupdateconf added to .scripts\033[0m"
fi

# update .bashrc
## Update the submodules
git submodule add git@github.com:Vivelis/MyBashrc.git &> /dev/null
git submodule update --init --recursive
git submodule update --remote --merge
## Replace the .bashrc file
if [ -f "~/.bashrc" ]; then
    # Backup the old file
    mv -f ~/.bashrc .bashrc.old
    echo -e "\033[33m~/.bashrc saved as .bashrc.old\033[0m"
fi
cp -f MyBashrc/.bashrc ~/.bashrc
echo -e "\033[34m~/.bashrc updated\033[0m"

echo -e "\033[32mUpdate finished\033[0m"
# Go back to the previous folder
cd - > /dev/null
